<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use App\Models\Item;
use App\Models\History;
use App\Models\RejectionComment;
use App\Rules\ValidBase64Image;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ItemController extends Controller
{

    public function index(Request $request): JsonResponse
    {
        $perPage = $request->input('per_page', 50); // Default 50 items per page
        $perPage = min(max((int)$perPage, 1), 100); // Limit between 1-100

        $items = Item::where('status', 'available')
                    ->orderBy('created_at', 'desc')
                    ->paginate($perPage);

        return response()->json([
            'data' => $items->items(),
            'pagination' => [
                'current_page' => $items->currentPage(),
                'last_page' => $items->lastPage(),
                'per_page' => $items->perPage(),
                'total' => $items->total(),
                'from' => $items->firstItem(),
                'to' => $items->lastItem()
            ]
        ]);
    }

    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'category' => 'required|string|max:100',
            'location' => 'required|string|max:200',
            'description' => 'required|string|max:1000',
            'date_time' => 'required|date',
            'is_valuable' => 'boolean',
            'image' => ['nullable', new ValidBase64Image(2)], // Max 2MB for memory optimization
            'finder_name' => 'nullable|string|max:100',
            'finder_grade' => 'nullable|string|max:100',
            'finder_id' => 'nullable|string|max:50',
            'officer' => 'nullable|string|max:100'
        ]);

        // item_no will be auto-generated by the model
        $validated['status'] = 'available';

        // Set officer from authenticated user if not provided
        if (empty($validated['officer'])) {
            $validated['officer'] = $request->input('auth_user_name', 'System');
        }

        // Compress image if present to save memory
        if (!empty($validated['image'])) {
            $validated['image'] = $this->compressBase64Image($validated['image']);
        }

        // Generate sequential item number starting from 1
        try {
            $validated['item_no'] = DB::transaction(function () {
                $maxItemNo = Item::max('item_no') ?? 0;
                return $maxItemNo + 1;
            });
            $item = Item::create($validated);
        } catch (\Exception $e) {
            Log::error('Item creation failed', ['error' => $e->getMessage()]);
            return response()->json([
                'success' => false,
                'message' => 'Failed to create item: ' . $e->getMessage()
            ], 500);
        }

        return response()->json([
            'success' => true,
            'data' => $item,
            'message' => 'Item created successfully'
        ], 201);
    }

    private function compressBase64Image($base64Image, $quality = 70)
    {
        try {
            
            if (preg_match('/^data:image\/(\w+);base64,/', $base64Image, $matches)) {
                $imageData = substr($base64Image, strpos($base64Image, ',') + 1);
                $imageData = base64_decode($imageData);
                
                
                $image = imagecreatefromstring($imageData);
                if (!$image) return $base64Image;
                
                
                $width = imagesx($image);
                $height = imagesy($image);
                
                
                if ($width > 800 || $height > 800) {
                    $ratio = min(800 / $width, 800 / $height);
                    $newWidth = (int)($width * $ratio);
                    $newHeight = (int)($height * $ratio);
                    
                    $resized = imagecreatetruecolor($newWidth, $newHeight);
                    imagecopyresampled($resized, $image, 0, 0, 0, 0, $newWidth, $newHeight, $width, $height);
                    imagedestroy($image);
                    $image = $resized;
                }
                
                // Compress and convert back to base64
                ob_start();
                imagejpeg($image, null, $quality);
                $compressedData = ob_get_contents();
                ob_end_clean();
                imagedestroy($image);
                
                return 'data:image/jpeg;base64,' . base64_encode($compressedData);
            }
        } catch (\Exception $e) {
            Log::warning('Image compression failed', ['error' => $e->getMessage()]);
        }
        
        return $base64Image;
    }

    public function show(Item $item): JsonResponse
    {
        return response()->json([
            'success' => true,
            'data' => $item
        ]);
    }

    public function update(Request $request, Item $item): JsonResponse
    {
        // Check if user is admin via header
        $isAdmin = $request->header('X-Is-Admin') === 'true';

        if (!$isAdmin) {
            return response()->json([
                'success' => false,
                'message' => 'Unauthorized. Only administrators can update items directly.'
            ], 403);
        }

        $validated = $request->validate([
            'category' => 'sometimes|string|max:100',
            'location' => 'sometimes|string|max:200',
            'description' => 'sometimes|string|max:1000',
            'date_time' => 'sometimes|date'
        ]);

        // Only update fields that are present
        $validated = array_filter($validated, function($value) {
            return $value !== null;
        });

        $item->update($validated);

        // Create history record for admin update
        History::create([
            'item_id' => $item->id,
            'date' => now()->toDateString(),
            'code' => $item->is_valuable ? 'V' : 'L',
            'item_name' => $item->category,
            'owner' => 'Admin',
            'status' => 'Admin Edit',
            'officer' => $request->input('auth_user_name', 'Admin')
        ]);

        return response()->json([
            'success' => true,
            'data' => $item,
            'message' => 'Item updated successfully'
        ]);
    }

    public function destroy(Request $request, Item $item): JsonResponse
    {
        // Authorization check: Only admins can delete items
        if (!$request->input('auth_is_admin')) {
            return response()->json([
                'success' => false,
                'message' => 'Unauthorized. Only administrators can delete items.'
            ], 403);
        }

        // Create history record before deletion
        History::create([
            'item_id' => $item->id,
            'date' => now()->toDateString(),
            'code' => $item->is_valuable ? 'V' : 'L',
            'item_name' => $item->category,
            'owner' => null,
            'status' => 'Deleted',
            'officer' => $request->input('auth_user_name', 'Admin')
        ]);

        $item->delete();

        return response()->json([
            'success' => true,
            'message' => 'Item deleted successfully'
        ]);
    }

    public function claim(Request $request, Item $item): JsonResponse
    {
        if ($item->status === 'claimed') {
            return response()->json([
                'success' => false,
                'message' => 'Item already claimed'
            ], 400);
        }

        try {
            $validated = $request->validate([
                'owner' => 'required|string|max:100',
                'claimer_name' => 'nullable|string|max:100',
                'claimer_grade' => 'nullable|string|max:100',
                'claimer_id' => 'nullable|string|max:50',
                'claim_date' => 'nullable|date'
            ]);
        } catch (\Illuminate\Validation\ValidationException $e) {
            return response()->json([
                'success' => false,
                'message' => 'Validation failed',
                'errors' => $e->errors()
            ], 400);
        }

        $item->update([
            'status' => 'claimed',
            'claimer_name' => $validated['claimer_name'] ?? $validated['owner'],
            'claimer_grade' => $validated['claimer_grade'] ?? null,
            'claimer_id' => $validated['claimer_id'] ?? null,
            'claim_date' => $validated['claim_date'] ?? now()
        ]);

        // Create history record for claim with authenticated user
        History::create([
            'item_id' => $item->id,
            'date' => now()->toDateString(),
            'code' => $item->is_valuable ? 'V' : 'L',
            'item_name' => $item->category,
            'owner' => $validated['owner'],
            'status' => 'Claimed',
            'officer' => $request->input('auth_user_name', 'Officer')
        ]);

        return response()->json([
            'success' => true,
            'data' => $item,
            'message' => 'Item claimed successfully'
        ]);
    }

    public function itemsToBeCleared(Request $request): JsonResponse
    {
        $perPage = $request->input('per_page', 50); // Default 50 items per page
        $perPage = min(max((int)$perPage, 1), 100); // Limit between 1-100

        $items = Item::available()
                    ->olderThan(7)
                    ->where('is_valuable', false)
                    ->select(['id', 'category', 'location', 'description', 'date_time', 'created_at'])
                    ->paginate($perPage);

        return response()->json([
            'success' => true,
            'data' => $items->items(),
            'pagination' => [
                'current_page' => $items->currentPage(),
                'last_page' => $items->lastPage(),
                'per_page' => $items->perPage(),
                'total' => $items->total(),
                'from' => $items->firstItem(),
                'to' => $items->lastItem()
            ]
        ]);
    }

    public function getHistory(Item $item): JsonResponse
    {
        $item->load('history');

        return response()->json([
            'success' => true,
            'data' => $item->history
        ]);
    }
    
    public function getAllHistory(Request $request): JsonResponse
    {
        $perPage = $request->input('per_page', 50); // Default 50 items per page
        $perPage = min(max((int)$perPage, 1), 100); // Limit between 1-100

        $historyQuery = History::with('item')
            ->whereNotIn('status', ['Approved', 'Handed Over'])
            ->orderBy('created_at', 'desc');

        $history = $historyQuery->paginate($perPage);

        $mappedData = $history->getCollection()->map(function ($historyRecord) {
            $item = $historyRecord->item;
            return [
                'id' => $historyRecord->id,
                'item_id' => $historyRecord->item_id,
                'item_no' => $item->item_no ?? null,
                'date' => $historyRecord->date,
                'code' => $historyRecord->code,
                'item_name' => $historyRecord->item_name,
                'category' => $item->category ?? null,
                'description' => $item->description ?? null,
                'location' => $item->location ?? null,
                'date_time' => $item->date_time ?? null,
                'image' => $item->image ?? null,
                'is_valuable' => $item->is_valuable ?? false,
                'finder_name' => $item->finder_name ?? null,
                'finder_grade' => $item->finder_grade ?? null,
                'finder_id' => $item->finder_id ?? null,
                'claimer_name' => $item->claimer_name ?? null,
                'claimer_grade' => $item->claimer_grade ?? null,
                'claimer_id' => $item->claimer_id ?? null,
                'claim_date' => $item->claim_date ?? null,
                'owner' => $historyRecord->owner,
                'status' => $historyRecord->status,
                'officer' => $historyRecord->officer,
                'created_at' => $historyRecord->created_at,
                'updated_at' => $historyRecord->updated_at
            ];
        });

        return response()->json([
            'success' => true,
            'data' => $mappedData,
            'pagination' => [
                'current_page' => $history->currentPage(),
                'last_page' => $history->lastPage(),
                'per_page' => $history->perPage(),
                'total' => $history->total(),
                'from' => $history->firstItem(),
                'to' => $history->lastItem()
            ]
        ]);
    }

    public function getRejectionComments($itemId): JsonResponse
    {
        $comments = RejectionComment::where('item_id', $itemId)
            ->orderBy('created_at', 'desc')
            ->get();

        return response()->json($comments);
    }
}