<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use App\Models\Item;
use App\Models\History;
use App\Rules\ValidBase64Image;
use Illuminate\Support\Facades\DB;

class ItemController extends Controller
{

    public function index(): JsonResponse
    {
        $items = Item::available()->get();
        return response()->json([
            'data' => $items
        ]);
    }

    public function store(Request $request): JsonResponse
    {
        $validated = $request->validate([
            'category' => 'required|string|max:100',
            'location' => 'required|string|max:200',
            'description' => 'required|string|max:1000',
            'date_time' => 'required|date',
            'is_valuable' => 'boolean',
            'image' => ['nullable', new ValidBase64Image(5)], // Max 5MB
            'finder_name' => 'nullable|string|max:100',
            'finder_grade' => 'nullable|string|max:100',
            'finder_id' => 'nullable|string|max:50',
            'officer' => 'nullable|string|max:100'
        ]);

        // item_no will be auto-generated by the model
        $validated['status'] = 'available';

        // Set officer from authenticated user if not provided
        if (empty($validated['officer'])) {
            $validated['officer'] = $request->input('auth_user_name', 'System');
        }

        // Retry logic to handle race conditions in item_no generation
        $maxAttempts = 5;
        $attempt = 0;
        $item = null;

        while ($attempt < $maxAttempts) {
            try {
                $item = DB::transaction(function () use ($validated) {
                    return Item::create($validated);
                });
                break; // Success, exit loop
            } catch (\Illuminate\Database\QueryException $e) {
                // Check if it's a unique constraint violation on item_no
                if (str_contains($e->getMessage(), 'UNIQUE constraint failed: items.item_no')) {
                    $attempt++;
                    if ($attempt >= $maxAttempts) {
                        throw $e; // Give up after max attempts
                    }
                    // Small delay before retry
                    usleep(50000); // 50ms
                    continue;
                }
                // If it's a different error, throw it immediately
                throw $e;
            }
        }

        return response()->json([
            'success' => true,
            'data' => $item,
            'message' => 'Item created successfully'
        ], 201);
    }

    public function show(Item $item): JsonResponse
    {
        return response()->json([
            'success' => true,
            'data' => $item
        ]);
    }

    public function update(Request $request, Item $item): JsonResponse
    {
        // Check if user is admin via header
        $isAdmin = $request->header('X-Is-Admin') === 'true';

        if (!$isAdmin) {
            return response()->json([
                'success' => false,
                'message' => 'Unauthorized. Only administrators can update items directly.'
            ], 403);
        }

        $validated = $request->validate([
            'category' => 'sometimes|string|max:100',
            'location' => 'sometimes|string|max:200',
            'description' => 'sometimes|string|max:1000',
            'date_time' => 'sometimes|date'
        ]);

        // Only update fields that are present
        $validated = array_filter($validated, function($value) {
            return $value !== null;
        });

        $item->update($validated);

        // Create history record for admin update
        History::create([
            'item_id' => $item->id,
            'date' => now()->toDateString(),
            'code' => $item->is_valuable ? 'V' : 'L',
            'item_name' => $item->category,
            'owner' => null,
            'status' => 'Updated',
            'officer' => $request->input('auth_user_name', 'Admin')
        ]);

        return response()->json([
            'success' => true,
            'data' => $item,
            'message' => 'Item updated successfully'
        ]);
    }

    public function destroy(Request $request, Item $item): JsonResponse
    {
        // Authorization check: Only admins can delete items
        if (!$request->input('auth_is_admin')) {
            return response()->json([
                'success' => false,
                'message' => 'Unauthorized. Only administrators can delete items.'
            ], 403);
        }

        // Create history record before deletion
        History::create([
            'item_id' => $item->id,
            'date' => now()->toDateString(),
            'code' => $item->is_valuable ? 'V' : 'L',
            'item_name' => $item->category,
            'owner' => null,
            'status' => 'Deleted',
            'officer' => $request->input('auth_user_name', 'Admin')
        ]);

        $item->delete();

        return response()->json([
            'success' => true,
            'message' => 'Item deleted successfully'
        ]);
    }

    public function claim(Request $request, Item $item): JsonResponse
    {
        if ($item->status === 'claimed') {
            return response()->json([
                'success' => false,
                'message' => 'Item already claimed'
            ], 400);
        }

        $validated = $request->validate([
            'owner' => 'required|string|max:100',
            'claimer_name' => 'nullable|string|max:100',
            'claimer_grade' => 'nullable|string|max:100',
            'claimer_id' => 'nullable|string|max:50',
            'claim_date' => 'nullable|date'
        ]);

        $item->update([
            'status' => 'claimed',
            'claimer_name' => $validated['claimer_name'] ?? $validated['owner'],
            'claimer_grade' => $validated['claimer_grade'] ?? null,
            'claimer_id' => $validated['claimer_id'] ?? null,
            'claim_date' => $validated['claim_date'] ?? now()
        ]);

        // Create history record for claim with authenticated user
        History::create([
            'item_id' => $item->id,
            'date' => now()->toDateString(),
            'code' => $item->is_valuable ? 'V' : 'L',
            'item_name' => $item->category,
            'owner' => $validated['owner'],
            'status' => 'Claimed',
            'officer' => $request->input('auth_user_name', 'Officer')
        ]);

        return response()->json([
            'success' => true,
            'data' => $item,
            'message' => 'Item claimed successfully'
        ]);
    }

    public function itemsToBeCleared(): JsonResponse
    {
        $items = Item::available()
                    ->olderThan(7)
                    ->where('is_valuable', false)
                    ->select(['id', 'category', 'location', 'description', 'date_time', 'created_at'])
                    ->get();
        
        return response()->json([
            'success' => true,
            'data' => $items
        ]);
    }

    public function getHistory(Item $item): JsonResponse
    {
        $item->load('history');

        return response()->json([
            'success' => true,
            'data' => $item->history
        ]);
    }
    
    public function getAllHistory(): JsonResponse
    {
        $history = History::with('item')
            ->orderBy('created_at', 'desc')
            ->get()
            ->map(function ($historyRecord) {
                $item = $historyRecord->item;
                return [
                    'id' => $historyRecord->id,
                    'item_id' => $historyRecord->item_id,
                    'item_no' => $item->item_no ?? null,
                    'date' => $historyRecord->date,
                    'code' => $historyRecord->code,
                    'item_name' => $historyRecord->item_name,
                    'category' => $item->category ?? null,
                    'description' => $item->description ?? null,
                    'location' => $item->location ?? null,
                    'date_time' => $item->date_time ?? null,
                    'image' => $item->image ?? null,
                    'is_valuable' => $item->is_valuable ?? false,
                    'finder_name' => $item->finder_name ?? null,
                    'finder_grade' => $item->finder_grade ?? null,
                    'finder_id' => $item->finder_id ?? null,
                    'claimer_name' => $item->claimer_name ?? null,
                    'claimer_grade' => $item->claimer_grade ?? null,
                    'claimer_id' => $item->claimer_id ?? null,
                    'claim_date' => $item->claim_date ?? null,
                    'owner' => $historyRecord->owner,
                    'status' => $historyRecord->status,
                    'officer' => $historyRecord->officer,
                    'created_at' => $historyRecord->created_at,
                    'updated_at' => $historyRecord->updated_at
                ];
            });
        
        return response()->json([
            'success' => true,
            'data' => $history
        ]);
    }
}